#ifndef VK2C_H
#define VK2C_H

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

typedef enum
{
    VK2C_OK = 0,

    VK2C_ERROR_GLFW_FAIlED,
    VK2C_ERROR_CREATE_GLFW_SURFACE_FAILED,

    VK2C_ERROR_QUERY_INSTANCE_LAYER_PROPERTIES_FAILED,
    VK2C_ERROR_QUERY_INSTANCE_EXTENSION_PROPERTIES_FAILED,
    VK2C_ERROR_SUITABLE_LAYER_NOT_FOUND,
    VK2C_ERROR_SUITABLE_EXTENSION_NOT_FOUND,
    VK2C_ERROR_CREATE_INSTANCE_FAILED,
    VK2C_ERROR_GET_INSTANCE_PROC_ADDRESS,

    VK2C_ERROR_CREATE_DEBUG_MESSENGER_FAILED,

    VK2C_ERROR_QUERY_PHYSICAL_DEVICES_FAILED,
    VK2C_ERROR_QUERY_PHYSICAL_DEVICE_LAYER_PROPERTIES_FAILED,
    VK2C_ERROR_QUERY_PHYSICAL_DEVICE_EXTENSION_PROPERTIES_FAILED,
    VK2C_ERROR_QUERY_PHYSICAL_DEVICE_SURFACE_CAPABILITIES_FAILED,
    VK2C_ERROR_QUERY_PHYSICAL_DEVICE_SURFACE_FORMAT_FAILED,
    VK2C_ERROR_QUERY_PHYSICAL_DEVICE_SURFACE_PRESENT_MODE_FAILED,

    VK2C_ERROR_CREATE_DEVICES_FAILED,
    VK2C_ERROR_DEVICE_QUEUE_NOT_FOUND,

    VK2C_ERROR_CREATE_SWAPCHAIN_FAILED,
    VK2C_ERROR_QUERY_SWAPCHAIN_IMAGES_FAILED,
    VK2C_ERROR_CREATE_SWAPCHAIN_IMAGES_FAILED,

    VK2C_ERROR_CREATE_RENDERPASS_FAILED,

    VK2C_ERROR_CREATE_FRAMEBUFFER_FAILED,

    VK2C_ERROR_SHADER_MODULE_NOT_FOUND,

    VK2C_ERROR_CREATE_GRAPHICS_PIPELINE_FAILED,
    VK2C_ERROR_CREATE_GRAHPICS_PIPELINE_LAYOUT_FAILED,

    VK2C_ERROR_OOM,
    VK2C_ERROR_UNKNOWN,
} VK2CResult_t;

typedef struct Vk2cContex Vk2cContex_t;

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // VK2C_H
